GET http://localhost:3003/character?name=Deadpool

###

PUT http://localhost:3003/character
Content-Type: application/json

{
    "name": "Juggernaut",
    "gender": "MALE",
    "description": "o irmão do Prof X!!"
}

###

DELETE http://localhost:3003/character/4